spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  #에플리케이션 실행 시점에 가지고 있던 테이블을 다 지우고 다시 생성
    properties:
      hibernate:
        #        show_sql: true # org.hibernate.SQL과의 차이점은 system.out을 통해 출력
        format_sql: true

logging.level:
  org.hibernate.SQL: debug #JPA나 hibernate가 생성하는 모든 SQL이 보이게 함,로그로 출력
  org.hibernate.type: trace # 쿼리 파라미터 로그 남기기